version: '3.8'
services:
  db:
    image: postgres:latest
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=${USERNAME_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${DATABASE}
    ports:
      - '54321:5432'
    volumes:
      - /var/lib/postgresql/data
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db