version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db